import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    Container, Editable,
    FormLabel,
    Heading,
    HStack,
    Input, InputGroup, InputRightAddon, InputRightElement,
    MenuItemOption, NumberDecrementStepper, NumberIncrementStepper, NumberInput, NumberInputField, NumberInputStepper,
    Select,
    Stack,
    Text,
    VStack
} from "@chakra-ui/react";
import {useState} from "react";

export default function Home() {
    const reflectWords = ['Adventurous', 'Anxious','Charitable', 'Confident', 'Connection', 'Courageous', 'Creative', 'Culture', 'Envious',
        'Exhausted', 'Family', 'Fear', 'Focused', 'Friendship', 'Growth', ' Happy', 'Healthy', 'Hopeful', 'Independent', 'Intelligent', 'Intense'
        ,'Leadership', 'Lonely', 'Lost', 'Love', 'Passionate', 'Peaceful', 'Positive', 'Powerful', 'Purposeful', ' Secure', 'Sharing', 'Spiritual',
        'Strong', 'Thankful', 'Transformative', 'Travel', 'Uncertain', ' Wealth']
    const dreamWords = ['Adventurous', 'Charitable', 'Community', 'Confident', 'Connection', 'Courageous', 'Creative', 'Culture', 'Family', 'Focused'
    , 'Friendship', 'Growth', 'Healthy', 'Hopeful', 'Intelligent', 'Leadership', 'Love', 'Passionate', 'Peaceful', 'Positive', 'Powerful'
    , 'Purposeful', 'Secure', 'Sharing', 'Spiritual', 'Strong', 'Thankful', 'Transformative', 'Travel', 'Wealth']

    const [title, setTitle] = useState('Start your reflection')

    function titleChangeHandler(event) {
        if(event.target.value == ""){
            setTitle("Start your reflection")
        }else{
            setTitle(`Howdy, ${event.target.value}`)
        }
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Lifepass Reflection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Container centerContent={true}>
              <Heading fontSize={'5xl'}>{title}</Heading>
          </Container>
          <Container>
              <VStack>
                  <Heading>What is your name </Heading>
                  <Input autoComplete={"new-password"} onChange={titleChangeHandler}/>

              </VStack>
              <VStack>
                  <Heading>Reflect Words</Heading>
                  <Text>How would you describe your past year</Text>
                  <HStack>
                      {/* Reflect Words*/}
                      <Select width={'200px'} >
                          <option></option>
                          {reflectWords.map((elem) => <option key={elem}>{elem}</option>)}
                      </Select>
                      <Select width={'200px'} >
                          <option></option>
                          {reflectWords.map((elem) => <option key={elem}>{elem}</option>)}
                      </Select>
                      <Select width={'200px'} >
                          <option></option>
                          {reflectWords.map((elem) => <option key={elem}>{elem}</option>)}
                      </Select>
                  </HStack>
              </VStack>
              <VStack>
                  <Heading>Dream Words</Heading>
                  <Text>Where do you want to go</Text>

                  <HStack>
                          {/* Dream Words*/}
                          <Select width={'200px'} >
                              <option></option>
                              {dreamWords.map((elem) => <option key={elem}>{elem}</option>)}
                          </Select>
                          <Select width={'200px'} >
                              <option></option>
                              {dreamWords.map((elem) => <option key={elem}>{elem}</option>)}
                          </Select>
                          <Select width={'200px'} >
                              <option></option>
                              {dreamWords.map((elem) => <option key={elem}>{elem}</option>)}
                          </Select>
                      </HStack>
              </VStack>
              <VStack>
                  <Heading>Time Analysis</Heading>
                  <Text>Out of 10 where did your time go</Text>
                  <VStack>
                      <HStack>
                          <Input />
                          <NumberInput defaultValue={1} min={1} max={10}>
                              <NumberInputField />
                              <NumberInputStepper>
                                  <NumberIncrementStepper />
                                  <NumberDecrementStepper />
                              </NumberInputStepper>
                          </NumberInput>
                      </HStack>
                  </VStack>
              </VStack>


          </Container>
      </main>

      {/*<main className={styles.main}>*/}
      {/*  <h1 className={styles.title}>*/}
      {/*    Welcome to <a href="https://nextjs.org">Next.js!</a>*/}
      {/*  </h1>*/}

      {/*  <p className={styles.description}>*/}
      {/*    Get started by editing{' '}*/}
      {/*    <code className={styles.code}>pages/index.js</code>*/}
      {/*  </p>*/}

      {/*  <div className={styles.grid}>*/}
      {/*    <a href="https://nextjs.org/docs" className={styles.card}>*/}
      {/*      <h2>Documentation &rarr;</h2>*/}
      {/*      <p>Find in-depth information about Next.js features and API.</p>*/}
      {/*    </a>*/}

      {/*    <a href="https://nextjs.org/learn" className={styles.card}>*/}
      {/*      <h2>Learn &rarr;</h2>*/}
      {/*      <p>Learn about Next.js in an interactive course with quizzes!</p>*/}
      {/*    </a>*/}

      {/*    <a*/}
      {/*      href="https://github.com/vercel/next.js/tree/canary/examples"*/}
      {/*      className={styles.card}*/}
      {/*    >*/}
      {/*      <h2>Examples &rarr;</h2>*/}
      {/*      <p>Discover and deploy boilerplate example Next.js projects.</p>*/}
      {/*    </a>*/}

      {/*    <a*/}
      {/*      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
      {/*      className={styles.card}*/}
      {/*    >*/}
      {/*      <h2>Deploy &rarr;</h2>*/}
      {/*      <p>*/}
      {/*        Instantly deploy your Next.js site to a public URL with Vercel.*/}
      {/*      </p>*/}
      {/*    </a>*/}
      {/*  </div>*/}
      {/*</main>*/}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
